- name: Run Powershell Scripts
  hosts: win
  vars:
    src_scripts: /mnt/c/scripts
    dest_scripts: c:\scripts\
  tasks:
  - name: Copy a single file
    win_copy:
      src: /mnt/c/scripts/0636920024132/Get-DiskUsage.ps1
      dest: C:\scripts\0636920024132\Get-DiskUsage.ps1
      remote_src: no

  - name: Copy a single file
    win_copy:
      src: '/mnt/c/Program Files (x86)/Jenkins/war/WEB-INF/lib/launchd-slave-installer-1.2.jar'
      dest: C:\launchd-slave-installer-1.2.jar
      remote_src: no      

  - name: run a powershell script
    win_shell: C:\scripts\0636920024132\Get-DiskUsage.ps1
    register: out
  - debug: var=out.stdout_lines

  - name: Find files with .txt extension using powershell wildcards
    win_find:
      paths: C:\temp
      patterns: [ '*.txt' ]
      recurse: yes
    register: findit
  - debug: var=findit

  - name: PowerShell Directory Test and File Create
    win_shell: |
      $value = Test-Path -Path C:\temp\test.txt
      if ($value) {
          write-host("FILE EXISTS")
        }else {
          New-Item C:\temp\test.txt -ItemType File      
      }
    register: testpath
  - debug: var=testpath.stdout_lines      

  - name: Copy a single file
    win_copy:
      src: "{{ playbook_dir }}/test_output.ps1"
      dest: C:\temp\test_output1.ps1
      remote_src: no

  - name: Run a script
    win_shell: C:\temp\test_output1.ps1
    register: result1
  - debug: var=result1.stdout_lines  

  - name: Process win_shell output
    set_fact:
      vms: "{{ result1.stdout | regex_findall('(?<=VM: )(.*)') }}"    
  - debug: var=vms      



